name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-versoin }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versoin }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: |
          touch .env
          echo "${{ secrets.PROD }}" > .env
  test:
    runs-on: self-hosted
    steps:
      - run: npm run test

  deploy:
    runs-on: self-hosted
    steps:
     - run: pm2 restart api